"""updated schema for winner selection

Revision ID: a577d4fce220
Revises: c68296ca12f8
Create Date: 2026-04-25 09:36:50.204619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a577d4fce220'
down_revision: Union[str, Sequence[str], None] = 'c68296ca12f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('winner_selection_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('selection_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'READY_TO_FINALIZE', 'FINALIZED', name='winnerselectionstatus'), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('winner_nomination_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['selection_id'], ['book_selections.id'], ),
    sa.ForeignKeyConstraint(['winner_nomination_id'], ['nominations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('selection_id')
    )
    op.create_index(op.f('ix_winner_selection_sessions_id'), 'winner_selection_sessions', ['id'], unique=False)
    op.create_table('winner_selection_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('eliminated_nomination_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['eliminated_nomination_id'], ['nominations.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['winner_selection_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'round_number', name='_session_round_number_uc')
    )
    op.create_index(op.f('ix_winner_selection_steps_id'), 'winner_selection_steps', ['id'], unique=False)
    op.create_table('winner_selection_step_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('nomination_id', sa.Integer(), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.Column('elimination_weight', sa.Float(), nullable=False),
    sa.Column('elimination_probability', sa.Float(), nullable=False),
    sa.Column('was_eliminated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['nomination_id'], ['nominations.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['winner_selection_steps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('step_id', 'nomination_id', name='_step_nomination_uc')
    )
    op.create_index(op.f('ix_winner_selection_step_candidates_id'), 'winner_selection_step_candidates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_winner_selection_step_candidates_id'), table_name='winner_selection_step_candidates')
    op.drop_table('winner_selection_step_candidates')
    op.drop_index(op.f('ix_winner_selection_steps_id'), table_name='winner_selection_steps')
    op.drop_table('winner_selection_steps')
    op.drop_index(op.f('ix_winner_selection_sessions_id'), table_name='winner_selection_sessions')
    op.drop_table('winner_selection_sessions')
    # ### end Alembic commands ###
