"""modified the books table to assign users to books

Revision ID: ae50c3420990
Revises: 77213b41b741
Create Date: 2026-05-04 18:41:16.906124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae50c3420990'
down_revision: Union[str, Sequence[str], None] = '77213b41b741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

FK_BOOKS_USER_ID_USERS = "fk_books_user_id_users"

def upgrade() -> None:

    with op.get_context().autocommit_block():
        op.execute(
            "ALTER TYPE public.roles ADD VALUE IF NOT EXISTS 'ADMIN'"
        )

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(FK_BOOKS_USER_ID_USERS, 'books', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(FK_BOOKS_USER_ID_USERS, 'books', type_='foreignkey')
    op.drop_column('books', 'user_id')
    # ### end Alembic commands ###
