"""added tg_id

Revision ID: c2f4f508f7ef
Revises: 0fe27be96853
Create Date: 2026-09-24 11:13:10.436584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2f4f508f7ef'
down_revision: Union[str, Sequence[str], None] = '0fe27be96853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_uploaded_files_id'), 'uploaded_files', ['id'], unique=False)
    op.add_column('users', sa.Column('tg_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tg_id')
    op.drop_index(op.f('ix_uploaded_files_id'), table_name='uploaded_files')
    # ### end Alembic commands ###
